// Generated by CoffeeScript 1.6.3
(function() {
  var error;

  app.data.db = new app.data.Db({
    config: {
      name: 'culturalMeTest',
      schema: {
        stores: [
          {
            name: 'incomes',
            keyPath: 'id',
            autoIncrement: true
          }
        ]
      }
    }
  });

  app.data.db.clear();

  error = function() {
    throw new Error('Ups... Something goes wrong...');
  };

  module("Balance model");

  asyncTest("Calculate balance", function() {
    var incomes, saved;
    expect(1);
    incomes = new app.models.Income({
      config: {
        proxy: new app.data.proxy.YdnDb({
          config: {
            db: app.data.db
          }
        })
      }
    });
    saved = function(response) {
      ok(response.id ? true : void 0, "Model created!");
      return start();
    };
    incomes.addListener('saved', saved.bind(incomes)).addListener('error', error.bind(incomes));
    incomes.setData({
      name: "Pay rate",
      value: 4000,
      date: +(new Date)
    });
    return incomes.save();
  });

}).call(this);

/*
//@ sourceMappingURL=test3-balance.map
*/
