// Generated by CoffeeScript 1.6.3
(function() {
  var Bar, app, yamvc,
    __slice = [].slice;

  app = window.app || {};

  app.views = app.views || {};

  yamvc = window.yamvc;

  Bar = yamvc.View.extend(function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.View.apply(this, all);
    return this;
  });

  Bar.prototype.init = function() {
    var all, config;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.View.prototype.init.apply(this, all);
    config = this.get('config');
    return config.views = {
      buttonExpense: new app.views.Button({
        config: {
          tpl: 'tpl-button',
          renderTo: '.add-expense',
          models: {
            locale: new yamvc.Model({
              config: {
                namespace: 'locale'
              },
              data: {
                text: 'Add Expense'
              }
            })
          }
        }
      }),
      buttonIncome: new app.views.Button({
        config: {
          tpl: 'tpl-button',
          renderTo: '.add-income',
          models: {
            locale: new yamvc.Model({
              config: {
                namespace: 'locale'
              },
              data: {
                text: 'Add Income'
              }
            })
          }
        }
      })
    };
  };

  app.views.Bar = Bar;

  window.app = app;

}).call(this);

/*
//@ sourceMappingURL=Bar.map
*/
