// Generated by CoffeeScript 1.6.3
(function() {
  var Chart, app, yamvc,
    __slice = [].slice;

  app = window.app || {};

  app.views = app.views || {};

  yamvc = window.yamvc;

  Chart = yamvc.View.extend(function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.View.apply(this, all);
    return this;
  });

  Chart.prototype.init = function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.View.prototype.init.apply(this, all);
    return this.bindEvents();
  };

  Chart.prototype.initConfig = function() {
    var all, config;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    config = this.get('config');
    config.models = {
      chart: app.models.chart
    };
    yamvc.View.prototype.initConfig.apply(this, all);
    return this.bindModelEvents();
  };

  Chart.prototype.bindEvents = function() {
    return this.addListener('render', this.initChart.bind(this));
  };

  Chart.prototype.bindModelEvents = function() {
    return this.getModel('chart').addListener('dataDataChange', this.redrawChart.bind(this));
  };

  Chart.prototype.redrawChart = function() {
    console.log('redraw!');
    return this.get('chart').draw(google.visualization.arrayToDataTable(this.getModel('chart').$get('data')), {
      title: this.getModel('chart').$get('title'),
      width: this.queryEl('.chart-container').offsetWidth,
      height: this.queryEl('.chart-container').offsetHeight,
      vAxis: {
        title: this.getModel('chart').$get('titlevAxis')
      },
      hAxis: {
        title: this.getModel('chart').$get('titlehAxis')
      }
    });
  };

  Chart.prototype.initChart = function() {
    var chart;
    chart = new google.visualization[this.getModel('chart').$get('type')](this.queryEl('.chart-container'));
    chart.draw(google.visualization.arrayToDataTable(this.getModel('chart').$get('data')), {
      title: this.getModel('chart').$get('title'),
      width: this.queryEl('.chart-container').offsetWidth,
      height: this.queryEl('.chart-container').offsetHeight,
      vAxis: {
        title: this.getModel('chart').$get('titlevAxis')
      },
      hAxis: {
        title: this.getModel('chart').$get('titlehAxis')
      }
    });
    this.set('chart', chart);
    return this.getModel('chart').load();
  };

  app.views.Chart = Chart;

  window.app = app;

}).call(this);

/*
//@ sourceMappingURL=Chart.map
*/
