// Generated by CoffeeScript 1.6.3
(function() {
  var Chart, app, yamvc,
    __slice = [].slice;

  app = window.app || {};

  app.views = app.views || {};

  yamvc = window.yamvc;

  Chart = yamvc.View.extend(function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.View.apply(this, all);
    return this;
  });

  Chart.prototype.init = function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.View.prototype.init.apply(this, all);
    return this.bindEvents();
  };

  Chart.prototype.initConfig = function() {
    var all, config;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    config = this.get('config');
    config.models = {
      chart: new app.models.Chart
    };
    return yamvc.View.prototype.initConfig.apply(this, all);
  };

  Chart.prototype.bindEvents = function() {
    return this.addListener('render', this.initChart.bind(this));
  };

  Chart.prototype.initChart = function() {
    var chart;
    chart = new google.visualization[this.getModel('chart').$get('type')](this.queryEl('.chart-container'));
    chart.draw(google.visualization.arrayToDataTable(this.getModel('chart').$get('data')), {
      title: this.getModel('chart').$get('title'),
      width: this.queryEl('.chart-container').offsetWidth,
      height: this.queryEl('.chart-container').offsetHeight,
      vAxis: {
        title: this.getModel('chart').$get('titlevAxis')
      },
      hAxis: {
        title: this.getModel('chart').$get('titlehAxis')
      }
    });
    return this.set('chart', chart);
  };

  app.views.Chart = Chart;

  window.app = app;

}).call(this);

/*
//@ sourceMappingURL=Chart.map
*/
