// Generated by CoffeeScript 1.6.3
(function() {
  var Layout, app, yamvc,
    __slice = [].slice;

  app = window.app || {};

  app.views = app.views || {};

  yamvc = window.yamvc;

  Layout = yamvc.View.extend(function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.View.apply(this, all);
    return this;
  });

  Layout.prototype.init = function() {
    var all, config, window, window2;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.View.prototype.init.apply(this, all);
    config = this.get('config');
    config.views = {
      barBalance: new app.views.BarBalance({
        config: {
          id: 'current-balance',
          tpl: 'tpl-bar-balance',
          renderTo: '.balance-container',
          models: {
            locale: new yamvc.Model({
              config: {
                namespace: 'locale'
              },
              data: {
                legend: 'Legend',
                expenses: 'expenses',
                resources: 'resources',
                currentBalance: 'Current balance'
              }
            }),
            balance: app.models.balance
          }
        }
      }),
      barActions: new app.views.Bar({
        config: {
          id: 'action-bar',
          tpl: 'tpl-bar-action',
          renderTo: '.layout-action-bar'
        }
      }),
      menu: new app.views.Menu({
        config: {
          id: 'menu',
          tpl: 'tpl-menu',
          renderTo: '.menu'
        }
      }),
      chart: new app.views.Chart({
        config: {
          id: 'dailyChart',
          tpl: 'tpl-chart',
          renderTo: '.container'
        }
      })
    };
    window = new app.views.window.AddIncome({
      config: {
        id: 'add-income',
        tpl: 'tpl-window',
        renderTo: 'body'
      }
    });
    window.render();
    window2 = new app.views.Window({
      config: {
        id: 'window-2',
        tpl: 'tpl-window',
        renderTo: 'body'
      }
    });
    return window2.render();
  };

  app.views.Layout = Layout;

  window.app = app;

}).call(this);

/*
//@ sourceMappingURL=Layout.map
*/
