// Generated by CoffeeScript 1.6.3
(function() {
  var Layout2, app, yamvc,
    __slice = [].slice;

  app = window.app || {};

  app.views = app.views || {};

  yamvc = window.yamvc;

  Layout2 = yamvc.View.extend(function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.View.apply(this, all);
    return this;
  });

  Layout2.prototype.init = function() {
    var all, config;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.View.prototype.init.apply(this, all);
    config = this.get('config');
    return config.views = {
      table: new app.views.Table
    };
  };

  app.views.Layout2 = Layout2;

  window.app = app;

}).call(this);

/*
//@ sourceMappingURL=Layout2.map
*/
