// Generated by CoffeeScript 1.6.3
(function() {
  var Window, app, yamvc,
    __slice = [].slice;

  app = window.app || {};

  app.views = app.views || {};

  yamvc = window.yamvc;

  Window = yamvc.View.extend(function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.View.apply(this, all);
    this.bindEvents();
    return this;
  });

  Window.prototype.bindEvents = function() {
    this.addListener('render', this.resize.bind(this));
    return this.addListener('render', this.bindClose.bind(this));
  };

  Window.prototype.initConfig = function() {
    var all, config;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    config = this.get('config');
    config.width = config.width || 400;
    config.height = config.height || 300;
    config.views = config.views || {};
    config.views.close = new app.views.Button({
      config: {
        tpl: 'tpl-button',
        renderTo: '.top-bar',
        models: {
          locale: new yamvc.Model({
            config: {
              namespace: 'locale'
            },
            data: {
              text: 'X'
            }
          })
        }
      }
    });
    config = this.get('config');
    config.height = 200;
    config.views = config.views || {};
    config.views.add = new app.views.Button({
      config: {
        tpl: 'tpl-button',
        renderTo: '.bottom-bar',
        models: {
          locale: new yamvc.Model({
            config: {
              namespace: 'locale'
            },
            data: {
              text: 'Add'
            }
          })
        }
      }
    });
    config.models = {
      locale: new yamvc.Model({
        config: {
          namespace: 'locale'
        },
        data: {
          name: 'Name',
          date: 'Date',
          value: 'Value',
          exName: 'e.g Salary',
          exDate: 'e.g 23/10/2019',
          exValue: 'e.g 2005.78'
        }
      })
    };
    return yamvc.View.prototype.initConfig.apply(this, all);
  };

  Window.prototype.bindClose = function() {
    var me;
    me = this;
    return this.queryEl('a').addEventListener('click', function(e) {
      e.preventDefault();
      me.hide();
      return this;
    }, true);
  };

  Window.prototype.resize = function() {
    var style;
    style = this.queryEl('.window-vertical-center').style;
    style.width = this.getWidth() + 'px';
    return style.height = this.getHeight() + 'px';
  };

  Window.prototype.show = function() {
    var style;
    style = this.get('el').style;
    return style.display = 'table';
  };

  Window.prototype.hide = function() {
    var style;
    style = this.get('el').style;
    return style.display = 'none';
  };

  app.views.Window = Window;

  window.app = app;

}).call(this);

/*
//@ sourceMappingURL=Window.map
*/
