// Generated by CoffeeScript 1.6.3
(function() {
  var DateHelper, app, yamvc,
    __slice = [].slice;

  app = window.app || {};

  app.logic = app.logic || {};

  yamvc = window.yamvc;

  DateHelper = yamvc.Core.extend(function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.Core.apply(this, all);
    return this;
  });

  DateHelper.prototype.daysInMonth = function(month, year) {
    return new Date(year, month, 0).getDate();
  };

  DateHelper.prototype.daysAgo = function(from, days) {
    return new Date(+new Date(from) - days * 24 * 60 * 60 * 1000);
  };

  DateHelper.prototype.parse = function(str) {
    var d, m, matchesNonPadded, matchesPadded, pad;
    pad = function(x) {
      var _ref;
      return ((_ref = ('' + x).length === 2) != null ? _ref : {
        '': '0'
      }) + x;
    };
    m = str.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
    d = m ? new Date(m[3], m[2] - 1, m[1]) : null;
    matchesPadded = d && (str === [pad(d.getDate()), pad(d.getMonth() + 1), d.getFullYear()].join('/'));
    matchesNonPadded = d && (str === [d.getDate(), d.getMonth() + 1, d.getFullYear()].join('/'));
    if (matchesPadded || matchesNonPadded) {
      return d;
    } else {
      return null;
    }
  };

  app.logic.Date = new DateHelper;

  window.app = app;

}).call(this);

/*
//@ sourceMappingURL=Date.map
*/
