// Generated by CoffeeScript 1.6.3
(function() {
  var Chart, app, yamvc,
    __slice = [].slice;

  app = window.app || {};

  app.models = app.models || {};

  yamvc = window.yamvc;

  Chart = yamvc.Model.extend(function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.Model.apply(this, all);
    return this;
  });

  Chart.prototype.init = function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return yamvc.Model.prototype.init.apply(this, all);
  };

  Chart.prototype.initConfig = function() {
    var all, config, initOpts;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    config = this.get('config');
    initOpts = this.get('initOpts');
    initOpts.data = {
      type: 'AreaChart',
      title: 'Daily balance',
      isStacked: true,
      data: [['Day', 'Balance'], ['1', 165], ['2', 135], ['3', 157], ['4', 139], ['5', 136], ['7', 136], ['8', 136], ['9', 136], ['10', 136], ['11', 136], ['12', 136], ['13', 136], ['14', 136], ['15', 136], ['16', 165], ['17', 135], ['18', 457], ['19', 139], ['20', 336], ['21', 136], ['22', 136], ['23', 136], ['24', 136], ['25', 136], ['26', 136], ['27', 136], ['28', 1936], ['29', 2136], ['30', 2136]]
    };
    config.namespace = 'balance';
    this.set('initOpts', initOpts);
    return yamvc.Model.prototype.initConfig.apply(this, all);
  };

  Chart.prototype.setRange = function(from, to) {};

  Chart.prototype.load = function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  };

  Chart.prototype.recaulculate = function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  };

  Chart.prototype.all = function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  };

  Chart.prototype.getChart = function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  };

  app.models.Chart = Chart;

  window.app = app;

}).call(this);

/*
//@ sourceMappingURL=Chart.map
*/
