// Generated by CoffeeScript 1.6.3
(function() {
  var Income, app, yamvc,
    __slice = [].slice;

  app = window.app || {};

  app.models = app.models || {};

  yamvc = window.yamvc;

  Income = yamvc.Model.extend(function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.Model.apply(this, all);
    return this;
  });

  Income.prototype.init = function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return yamvc.Model.prototype.init.apply(this, all);
  };

  Income.prototype.initConfig = function() {
    var all, config, opts;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    config = this.get('config');
    opts = this.get('initOpts');
    config.namespace = 'incomes';
    opts.data = opts.data || {};
    opts.data.date = opts.data.date || +(new Date);
    return yamvc.Model.prototype.initConfig.apply(this, all);
  };

  app.models.Income = Income;

  window.app = app;

}).call(this);

/*
//@ sourceMappingURL=Income.map
*/
