// Generated by CoffeeScript 1.6.3
(function() {
  var Incomes, app, yamvc,
    __slice = [].slice;

  app = window.app || {};

  app.models = app.models || {};

  yamvc = window.yamvc;

  Incomes = yamvc.Model.extend(function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    yamvc.Model.apply(this, all);
    return this;
  });

  Incomes.prototype.init = function() {
    var all;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return yamvc.Model.prototype.init.apply(this, all);
  };

  Incomes.prototype.initConfig = function() {
    var all, config;
    all = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    config = this.get('config');
    config.namespace = 'incomes';
    return yamvc.Model.prototype.initConfig.apply(this, all);
  };

  app.models.Incomes = Incomes;

  window.app = app;

}).call(this);

/*
//@ sourceMappingURL=Incomes.map
*/
