// Generated by CoffeeScript 1.6.3
(function() {
  var app, yamvc;

  app = window.app || {};

  yamvc = window.yamvc;

  app.init = function() {
    app.data.db = new app.data.Db({
      config: {
        name: 'culturalMe',
        schema: {
          stores: [
            {
              name: 'incomes',
              keyPath: 'id',
              autoIncrement: true,
              indexes: [
                {
                  keyPath: 'date'
                }
              ]
            }, {
              name: 'expenses',
              keyPath: 'id',
              autoIncrement: true,
              indexes: [
                {
                  keyPath: 'date'
                }
              ]
            }
          ]
        }
      }
    });
    app.layout = new app.views.Layout({
      config: {
        autoCreate: true,
        tpl: 'tpl-layout',
        renderTo: '#container'
      }
    });
    app.income = new app.views.form.AddIncome({
      config: {
        autoCreate: true,
        id: 'add-income',
        tpl: 'tpl-window',
        renderTo: 'body'
      }
    });
    app.income.render();
    app.expense = new app.views.form.AddExpense({
      config: {
        autoCreate: true,
        id: 'add-expense',
        tpl: 'tpl-window',
        renderTo: 'body'
      }
    });
    app.expense.render();
    app.controlles = {
      main: new yamvc.Controller({
        config: {
          name: 'Main',
          views: {
            layout: app.layout
          },
          events: {
            $layout: {
              render: function() {
                app.models.balance.load();
                return setTimeout(function() {
                  return app.mask.hide();
                }, 500);
              }
            },
            '.add-expense a': {
              click: function(view, e) {
                e.preventDefault();
                return this.onExpenseBtnClick();
              }
            },
            '.add-income a': {
              click: function(view, e) {
                e.preventDefault();
                return this.onIncomeBtnClick();
              }
            },
            '[yamvc-id="list-incomes"] a': {
              click: function(view, e) {
                e.preventDefault();
                return this.onListIncomesBtnClick();
              }
            },
            '[yamvc-id="list-expenses"] a': {
              click: function(view, e) {
                e.preventDefault();
                return this.onListExpensesBtnClick();
              }
            }
          }
        },
        onExpenseBtnClick: function() {
          return yamvc.ViewManager.get('add-expense').show();
        },
        onIncomeBtnClick: function() {
          return yamvc.ViewManager.get('add-income').show();
        },
        onListIncomesBtnClick: function() {
          return console.log('list incomes click');
        },
        onListExpensesBtnClick: function() {
          return console.log('list expenses click');
        }
      })
    };
    return this;
  };

  window.app = app;

  yamvc.onReady(app.init);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
